"""Compatibility facade for legacy ``app.services.importer`` imports."""

from typeshift.core.importers.url import (
    AliExpressClient,
    AmazonRapidApiClient,
    ApiConfig,
    Media,
    Money,
    Price,
    Product,
    ProductClient,
    ProductClientFactory,
    SquarespaceClient,
    ShopifyClient,
    Variant,
    Weight,
    WooCommerceClient,
    _parse_aliexpress_result,
    detect_product_url,
    fetch_product_details,
    format_decimal,
    import_product,
    import_product_from_url,
    import_products_from_urls,
    normalize_currency,
    normalize_product_url,
    parse_decimal_money,
    requires_rapidapi,
)

__all__ = [
    "AliExpressClient",
    "AmazonRapidApiClient",
    "ApiConfig",
    "Media",
    "Money",
    "Price",
    "Product",
    "ProductClient",
    "ProductClientFactory",
    "SquarespaceClient",
    "ShopifyClient",
    "Variant",
    "Weight",
    "WooCommerceClient",
    "_parse_aliexpress_result",
    "detect_product_url",
    "fetch_product_details",
    "format_decimal",
    "import_product",
    "import_product_from_url",
    "import_products_from_urls",
    "normalize_currency",
    "normalize_product_url",
    "parse_decimal_money",
    "requires_rapidapi",
]
