BIGCOMMERCE_COLUMNS: list[str] = [
    "Item",
    "ID",
    "Name",
    "Type",
    "SKU",
    "Options",
    "Inventory Tracking",
    "Current Stock",
    "Low Stock",
    "Price",
    "Cost Price",
    "Retail Price",
    "Sale Price",
    "Brand ID",
    "Channels",
    "Categories",
    "Description",
    "Custom Fields",
    "Page Title",
    "Product URL",
    "Meta Description",
    "Search Keywords",
    "Meta Keywords",
    "Bin Picking Number",
    "UPC/EAN",
    "Global Trade Number",
    "Manufacturer Part Number",
    "Free Shipping",
    "Fixed Shipping Cost",
    "Weight",
    "Width",
    "Height",
    "Depth",
    "Is Visible",
    "Is Featured",
    "Warranty",
    "Tax Class",
    "Product Condition",
    "Show Product Condition",
    "Sort Order",
    "Variant Image URL",
    "Internal Image URL (Export)",
    "Image URL (Import)",
    "Image Description",
    "Image is Thumbnail",
    "Image Sort Order",
    "YouTube ID",
    "Video Title",
    "Video Description",
    "Video Sort Order",
]

BIGCOMMERCE_LEGACY_COLUMNS: list[str] = [
    "Item Type",
    "Product ID",
    "Product Name",
    "Product Type",
    "Product Code/SKU",
    "Bin Picking Number",
    "Brand Name",
    "Option Set",
    "Option Set Align",
    "Product Description",
    "Price",
    "Cost Price",
    "Retail Price",
    "Sale Price",
    "Fixed Shipping Cost",
    "Free Shipping",
    "Product Warranty",
    "Product Weight",
    "Product Width",
    "Product Height",
    "Product Depth",
    "Allow Purchases?",
    "Product Visible?",
    "Product Availability",
    "Track Inventory",
    "Current Stock Level",
    "Low Stock Level",
    "Category",
    "Product Image ID - 1",
    "Product Image File - 1",
    "Product Image Description - 1",
    "Product Image Is Thumbnail - 1",
    "Product Image Sort - 1",
    "Product Image ID - 2",
    "Product Image File - 2",
    "Product Image Description - 2",
    "Product Image Is Thumbnail - 2",
    "Product Image Sort - 2",
    "Search Keywords",
    "Page Title",
    "Meta Keywords",
    "Meta Description",
    "MYOB Asset Acct",
    "MYOB Income Acct",
    "MYOB Expense Acct",
    "Product Condition",
    "Show Product Condition?",
    "Event Date Required?",
    "Event Date Name",
    "Event Date Is Limited?",
    "Event Date Start Date",
    "Event Date End Date",
    "Sort Order",
    "Product Tax Class",
    "Product UPC/EAN",
    "Stop Processing Rules",
    "Product URL",
    "Redirect Old URL?",
    "Global Trade Item Number",
    "Manufacturer Part Number",
]

BIGCOMMERCE_MODERN_REQUIRED_HEADERS = ("Item", "Name", "Type", "SKU", "Price")
BIGCOMMERCE_LEGACY_REQUIRED_HEADERS = ("Product Type", "Code", "Name", "Calculated Price")
BIGCOMMERCE_MODERN_DETECTION_HEADERS = {"Item", "SKU", "Name"}
BIGCOMMERCE_LEGACY_DETECTION_HEADERS = {"Product Type", "Code", "Name"}

BIGCOMMERCE_MODERN_HEADER_ALIASES: dict[str, tuple[str, ...]] = {
    "item": ("Item",),
    "id": ("ID",),
    "product_url": ("Product URL",),
    "name": ("Name",),
    "description": ("Description",),
    "page_title": ("Page Title",),
    "meta_description": ("Meta Description",),
    "search_keywords": ("Search Keywords",),
    "categories": ("Categories",),
    "type": ("Type",),
    "is_visible": ("Is Visible",),
    "sku": ("SKU",),
    "price": ("Price",),
    "weight": ("Weight",),
    "current_stock": ("Current Stock",),
    "options": ("Options",),
    "variant_image_url": ("Variant Image URL",),
    "image_url_import": ("Image URL (Import)",),
}

BIGCOMMERCE_LEGACY_HEADER_ALIASES: dict[str, tuple[str, ...]] = {
    "product_id": ("Product ID",),
    "product_url": ("Product URL",),
    "name": ("Name", "Product Name"),
    "description": ("Description", "Product Description"),
    "page_title": ("Page Title",),
    "meta_description": ("META Description", "Meta Description"),
    "brand": ("Brand", "Brand Name"),
    "meta_keywords": ("META Keywords", "Meta Keywords"),
    "category_details": ("Category Details", "Category"),
    "code": ("Code", "Product Code/SKU"),
    "calculated_price": ("Calculated Price", "Price"),
    "sale_price": ("Sale Price",),
    "retail_price": ("Retail Price",),
    "stock_level": ("Stock Level", "Current Stock Level"),
    "weight": ("Weight", "Product Weight"),
    "product_visible": ("Product Visible", "Product Visible?"),
    "images": ("Images",),
}
