SHOPIFY_COLUMNS: list[str] = [
    "Title",
    "URL handle",
    "Description",
    "Vendor",
    "Product category",
    "Type",
    "Tags",
    "Published on online store",
    "Status",
    "SKU",
    "Barcode",
    "Option1 name",
    "Option1 value",
    "Option1 Linked To",
    "Option2 name",
    "Option2 value",
    "Option2 Linked To",
    "Option3 name",
    "Option3 value",
    "Option3 Linked To",
    "Price",
    "Compare-at price",
    "Cost per item",
    "Charge tax",
    "Tax code",
    "Unit price total measure",
    "Unit price total measure unit",
    "Unit price base measure",
    "Unit price base measure unit",
    "Inventory tracker",
    "Inventory quantity",
    "Continue selling when out of stock",
    "Weight value (grams)",
    "Weight unit for display",
    "Requires shipping",
    "Fulfillment service",
    "Product image URL",
    "Image position",
    "Image alt text",
    "Variant image URL",
    "Gift card",
    "SEO title",
    "SEO description",
    "Color (product.metafields.shopify.color-pattern)",
    "Google Shopping / Google product category",
    "Google Shopping / Gender",
    "Google Shopping / Age group",
    "Google Shopping / Manufacturer part number (MPN)",
    "Google Shopping / Ad group name",
    "Google Shopping / Ads labels",
    "Google Shopping / Condition",
    "Google Shopping / Custom product",
    "Google Shopping / Custom label 0",
    "Google Shopping / Custom label 1",
    "Google Shopping / Custom label 2",
    "Google Shopping / Custom label 3",
    "Google Shopping / Custom label 4",
]

SHOPIFY_LEGACY_COLUMNS: set[str] = {
    "Handle",
    "Title",
    "Body (HTML)",
    "Vendor",
    "Type",
    "Tags",
    "Published",
    "Status",
    "Option1 Name",
    "Option1 Value",
    "Option2 Name",
    "Option2 Value",
    "Option3 Name",
    "Option3 Value",
    "Variant SKU",
    "Variant Grams",
    "Variant Inventory Tracker",
    "Variant Inventory Qty",
    "Variant Inventory Policy",
    "Variant Fulfillment Service",
    "Variant Price",
    "Variant Requires Shipping",
    "Variant Taxable",
    "Image Src",
    "Image Position",
    "Image Alt Text",
    "Variant Image",
    "Variant Weight Unit",
}

SHOPIFY_REQUIRED_HEADERS_OLD = (
    "Handle",
    "Title",
    "Body (HTML)",
    "Variant SKU",
    "Variant Price",
)
SHOPIFY_REQUIRED_HEADERS_NEW = ("URL handle", "Title", "Description", "SKU", "Price")
SHOPIFY_DETECTION_HEADERS_NEW = ("URL handle", "Title", "SKU", "Price")

SHOPIFY_HEADER_ALIASES: dict[str, tuple[str, ...]] = {
    "handle": ("Handle", "URL handle"),
    "title": ("Title",),
    "description": ("Body (HTML)", "Description"),
    "vendor": ("Vendor",),
    "product_category": ("Product category",),
    "tags": ("Tags",),
    "published": ("Published", "Published on online store"),
    "variant_sku": ("Variant SKU", "SKU"),
    "variant_price": ("Variant Price", "Price"),
    "variant_inventory_qty": ("Variant Inventory Qty", "Inventory quantity"),
    "variant_weight_grams": ("Variant Grams", "Weight value (grams)"),
    "variant_image": ("Variant Image", "Variant image URL"),
    "product_image": ("Image Src", "Product image URL"),
    "requires_shipping": ("Variant Requires Shipping", "Requires shipping"),
}

SHOPIFY_OPTION_NAME_TEMPLATES: tuple[str, ...] = ("Option{i} Name", "Option{i} name")
SHOPIFY_OPTION_VALUE_TEMPLATES: tuple[str, ...] = ("Option{i} Value", "Option{i} value")
