SQUARESPACE_COLUMNS: list[str] = [
    "Product ID [Non Editable]",
    "Variant ID [Non Editable]",
    "Product Type [Non Editable]",
    "Product Page",
    "Product URL",
    "Title",
    "Description",
    "SKU",
    "Option Name 1",
    "Option Value 1",
    "Option Name 2",
    "Option Value 2",
    "Option Name 3",
    "Option Value 3",
    "Option Name 4",
    "Option Value 4",
    "Option Name 5",
    "Option Value 5",
    "Option Name 6",
    "Option Value 6",
    "Price",
    "Sale Price",
    "On Sale",
    "Stock",
    "Categories",
    "Tags",
    "Weight",
    "Length",
    "Width",
    "Height",
    "Visible",
    "Hosted Image URLs",
]

SQUARESPACE_REQUIRED_HEADERS = (
    "Title",
    "SKU",
    "Price",
    "Product Type [Non Editable]",
    "Visible",
)
SQUARESPACE_HEADER_ALIASES: dict[str, tuple[str, ...]] = {
    "product_id": ("Product ID [Non Editable]",),
    "variant_id": ("Variant ID [Non Editable]",),
    "product_type": ("Product Type [Non Editable]",),
    "product_url": ("Product URL",),
    "title": ("Title",),
    "description": ("Description",),
    "sku": ("SKU",),
    "price": ("Price",),
    "stock": ("Stock",),
    "categories": ("Categories",),
    "tags": ("Tags",),
    "weight": ("Weight",),
    "visible": ("Visible",),
    "hosted_image_urls": ("Hosted Image URLs",),
}
SQUARESPACE_OPTION_NAME_TEMPLATE = "Option Name {i}"
SQUARESPACE_OPTION_VALUE_TEMPLATE = "Option Value {i}"
